[package]
name = "pydj_server"
version = "0.1.0"
rust-version = { workspace = true }
license = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
tower-lsp = "0.20.0"
tokio = {workspace = true}
